---
- name: Migrate projects
  hosts: localhost
  tasks: 

  - name: get template AAP 
    uri:
      url: http://192.168.18.248/api/v2/job_templates/
      headers:
        Authorization: 'Basic YWRtaW46cGFzc3dvcmQ='
      status_code: [200]
      method: GET
      validate_certs: no
    register: register_templates

  - name: validate name template import
    debug:
      msg: "{{ item.name }}"
    with_items: "{{ register_templates.json.results }}"

  - name: get projects AAP 
    uri:
      url: http://192.168.18.248/api/v2/projects/
      headers:
        Authorization: 'Basic YWRtaW46cGFzc3dvcmQ='
      status_code: [200]
      method: GET
      validate_certs: no
    register: register_projects

  - name: validate name project import
    set_fact:
      project_json: "{{ register_projects.json.results }}"

  - name: tareas por template
    include_tasks: tasks-migrate-template.yml
    loop: "{{ register_templates.json.results }}"
    loop_control:
      loop_var: job_template



    


